use db24;

/*DELIMITER $$
CREATE TRIGGER MyTBL_7A_guard1 BEFORE INSERT ON MyTBL_7A
FOR EACH ROW
BEGIN
DECLARE a varchar(100);
SELECT CURRENT_USER() INTO @a;
SIGNAL SQLSTATE '50000' SET message_text=@a;
END;$$
DELIMITER ;

INSERT INTO MyTBL_7A (FName) VALUE ('AAA');*/

CREATE TABLE `MyTBL_7B` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FName` varchar(255) DEFAULT NULL,
  `LName` varchar(255) DEFAULT NULL,
  `City` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

